name: travel_flutter_app
description: LocationPal - Your travel companion for discovering places and viewing Wikipedia content
publish_to: 'none'
version: 1.0.7+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  http: ^1.1.0
  url_launcher: ^6.2.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^11.0.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.0.0
  flutter_local_notifications: ^17.0.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
